// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPost struct {
	Title  string `json:"title"`
	Body   string `json:"body"`
	UserID string `json:"userId"`
}

type NewUser struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}
