// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Coba struct {
	ID string `json:"ID"`
}

type CobaQuery struct {
	Coba []*Coba `json:"coba"`
}

type NewUser struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}
